"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main.py']
#自寫模塊放在DATA_FILES列表中
DATA_FILES = ['postboy.py', 'postboy_ui.py']
# 第三方庫放在OPTIONS下的includes對應的列表中
OPTIONS = {'includes': ['PyQt5.QtCore', 'PyQt5.QtGui', 'PyQt5.QtWidgets']}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
